trigger:
- main

pool:

  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'ingeera/webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureResourceGroup: 'networking-resource-group'
        kubernetesCluster: 'terraform-aks-cluster'
        manifests: 'application-manifest.yaml'